apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.secretProviderClassName }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.keyVault.name | quote }}
    tenantId: {{ .Values.workloadIdentity.tenantId | quote }}
    objects: |
      array:
{{- range .Values.keyVault.objects }}
        - |
          objectName: {{ .secretName | quote }}
          objectType: secret
{{- end }}
  secretObjects:
    - secretName: {{ include "property-management.fullname" . }}-secrets
      type: Opaque
      data:
{{- range .Values.keyVault.objects }}
        - objectName: {{ .secretName | quote }}
          key: {{ .envName }}
{{- end }}
