config:
  WEBHOOK_BASE_URL: https://pm.betterdeal.ai
  ERPNEXT_BASE_URL: https://erpnext.example.com

ingress:
  hosts:
    - host: pm.betterdeal.ai
      paths:
        - path: /
          pathType: Prefix
